api_platform:
    resource: .
    type: api_platform
    prefix: /doc

#api
api_login_check:
    path: /api/login_check

register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: POST

